// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Riva.AdministrativeDivisions.Infrastructure.DataAccess.RivaAdministrativeDivisionsSqlServer.Contexts;

namespace Riva.AdministrativeDivisions.Infrastructure.DataAccess.RivaAdministrativeDivisionsSqlServer.Migrations
{
    [DbContext(typeof(RivaAdministrativeDivisionsDbContext))]
    partial class RivaAdministrativeDivisionsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Riva.AdministrativeDivisions.Infrastructure.DataAccess.RivaAdministrativeDivisionsSqlServer.Entities.CityDistrictEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PolishName")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("Name", "ParentId", "CityId")
                        .IsUnique()
                        .HasFilter("[ParentId] IS NOT NULL");

                    b.HasIndex("PolishName", "ParentId", "CityId")
                        .IsUnique()
                        .HasFilter("[ParentId] IS NOT NULL");

                    b.ToTable("CityDistricts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6dacf67a-ba5f-4bff-ac7f-95ed6fd4f889"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Fabryczna",
                            PolishName = "Fabryczna"
                        },
                        new
                        {
                            Id = new Guid("21db1b78-4a25-4f04-a6e3-31314bc45f94"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Krzyki",
                            PolishName = "Krzyki"
                        },
                        new
                        {
                            Id = new Guid("fc53428e-b09a-44fa-bff7-44379a6240ab"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Psie-Pole",
                            PolishName = "Psie Pole"
                        },
                        new
                        {
                            Id = new Guid("0a098de4-92e4-4ef8-887a-141aaf11f8dc"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Stare-Miasto",
                            PolishName = "Stare Miasto"
                        },
                        new
                        {
                            Id = new Guid("0a6a49ca-7508-49a8-bfae-3a995076943d"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Srodmiescie",
                            PolishName = "Śródmieście"
                        },
                        new
                        {
                            Id = new Guid("882cc824-1d0b-4acd-89d0-c846b98ab946"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Gajowice",
                            ParentId = new Guid("6dacf67a-ba5f-4bff-ac7f-95ed6fd4f889"),
                            PolishName = "Gajowice"
                        },
                        new
                        {
                            Id = new Guid("e5e77c3d-bb85-4c7a-868e-43e5d6f623cc"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Gadow-Popowice-Poludniowe",
                            ParentId = new Guid("6dacf67a-ba5f-4bff-ac7f-95ed6fd4f889"),
                            PolishName = "Gądów-Popowice Południowe"
                        },
                        new
                        {
                            Id = new Guid("c75ff32f-6ee3-4347-86b4-1aa0a96651a7"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Grabiszyn-Grabiszynek",
                            ParentId = new Guid("6dacf67a-ba5f-4bff-ac7f-95ed6fd4f889"),
                            PolishName = "Grabiszyn-Grabiszynek"
                        },
                        new
                        {
                            Id = new Guid("e3496408-fce3-4fee-b42b-3b0f529426e9"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Jerzmanowo-Jarnoltow-Strachowice-Osiniec",
                            ParentId = new Guid("6dacf67a-ba5f-4bff-ac7f-95ed6fd4f889"),
                            PolishName = "Jerzmanowo-Jarnołtów-Strachowice-Osiniec"
                        },
                        new
                        {
                            Id = new Guid("f6c8b915-38cd-44d8-878d-115cc440c5d3"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Kuzniki",
                            ParentId = new Guid("6dacf67a-ba5f-4bff-ac7f-95ed6fd4f889"),
                            PolishName = "Kuźniki"
                        },
                        new
                        {
                            Id = new Guid("c24e2403-5fc2-4e1a-bbf5-d4c510847742"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Lesnica",
                            ParentId = new Guid("6dacf67a-ba5f-4bff-ac7f-95ed6fd4f889"),
                            PolishName = "Leśnica"
                        },
                        new
                        {
                            Id = new Guid("4a7cfa64-3c42-46d7-b694-f6b8eccb5ab6"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Maslice",
                            ParentId = new Guid("6dacf67a-ba5f-4bff-ac7f-95ed6fd4f889"),
                            PolishName = "Maślice"
                        },
                        new
                        {
                            Id = new Guid("a45a6df5-4695-4db2-a362-c0477eab1c8b"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Muchobor-Maly",
                            ParentId = new Guid("6dacf67a-ba5f-4bff-ac7f-95ed6fd4f889"),
                            PolishName = "Muchobór Mały"
                        },
                        new
                        {
                            Id = new Guid("96adb77d-8505-46fc-9515-41fee1f06a6a"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Muchobor-Wielki",
                            ParentId = new Guid("6dacf67a-ba5f-4bff-ac7f-95ed6fd4f889"),
                            PolishName = "Muchobór Wielki"
                        },
                        new
                        {
                            Id = new Guid("aa5f1748-d858-45c6-b1bd-fd68d98c8b38"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Nowy-Dwor",
                            ParentId = new Guid("6dacf67a-ba5f-4bff-ac7f-95ed6fd4f889"),
                            PolishName = "Nowy Dwór"
                        },
                        new
                        {
                            Id = new Guid("66f68e3a-50cf-49cd-8191-e1fc627ea2e4"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Oporow",
                            ParentId = new Guid("6dacf67a-ba5f-4bff-ac7f-95ed6fd4f889"),
                            PolishName = "Oporów"
                        },
                        new
                        {
                            Id = new Guid("1019e1be-57d7-4ca6-9b38-f5da790eaa33"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Pilczyce-Kozanow-Popowice-Polnocne",
                            ParentId = new Guid("6dacf67a-ba5f-4bff-ac7f-95ed6fd4f889"),
                            PolishName = "Pilczyce-Kozanów-Popowice Północne"
                        },
                        new
                        {
                            Id = new Guid("e8858102-054a-4779-9760-7380ecf08df3"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Pracze-Odrzanskie",
                            ParentId = new Guid("6dacf67a-ba5f-4bff-ac7f-95ed6fd4f889"),
                            PolishName = "Pracze Odrzańskie"
                        },
                        new
                        {
                            Id = new Guid("7dea11fb-65ed-4b98-a06c-cfd01917b655"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Zerniki",
                            ParentId = new Guid("6dacf67a-ba5f-4bff-ac7f-95ed6fd4f889"),
                            PolishName = "Żerniki"
                        },
                        new
                        {
                            Id = new Guid("853f916a-3fbd-4baf-8a09-f29eee498966"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Bienkowice",
                            ParentId = new Guid("21db1b78-4a25-4f04-a6e3-31314bc45f94"),
                            PolishName = "Bieńkowice"
                        },
                        new
                        {
                            Id = new Guid("7f7e9487-cb8d-489b-8a58-827756622895"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Borek",
                            ParentId = new Guid("21db1b78-4a25-4f04-a6e3-31314bc45f94"),
                            PolishName = "Borek"
                        },
                        new
                        {
                            Id = new Guid("a25aa6e2-70dd-413f-9b00-949042b14f97"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Brochow",
                            ParentId = new Guid("21db1b78-4a25-4f04-a6e3-31314bc45f94"),
                            PolishName = "Brochów"
                        },
                        new
                        {
                            Id = new Guid("69c05563-4af9-4552-b43d-b742dc33a91f"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Gaj",
                            ParentId = new Guid("21db1b78-4a25-4f04-a6e3-31314bc45f94"),
                            PolishName = "Gaj"
                        },
                        new
                        {
                            Id = new Guid("88dd1ffd-00f4-469b-ae94-745e2a336ddb"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Huby",
                            ParentId = new Guid("21db1b78-4a25-4f04-a6e3-31314bc45f94"),
                            PolishName = "Huby"
                        },
                        new
                        {
                            Id = new Guid("0a77f641-5227-4f4e-8f89-91d431218daa"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Jagodno",
                            ParentId = new Guid("21db1b78-4a25-4f04-a6e3-31314bc45f94"),
                            PolishName = "Jagodno"
                        },
                        new
                        {
                            Id = new Guid("59a2d9a7-e6dd-4b8e-b1e7-47e88f18e0dc"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Klecina",
                            ParentId = new Guid("21db1b78-4a25-4f04-a6e3-31314bc45f94"),
                            PolishName = "Klecina"
                        },
                        new
                        {
                            Id = new Guid("ac5d8893-9370-4546-bbb5-51edc01a442c"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Krzyki-Partynice",
                            ParentId = new Guid("21db1b78-4a25-4f04-a6e3-31314bc45f94"),
                            PolishName = "Krzyki-Partynice"
                        },
                        new
                        {
                            Id = new Guid("83bd3deb-0f48-4846-8eaf-54ade5b90915"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Ksieze",
                            ParentId = new Guid("21db1b78-4a25-4f04-a6e3-31314bc45f94"),
                            PolishName = "Księże"
                        },
                        new
                        {
                            Id = new Guid("25fb993b-700f-45be-8699-c09881f7a76c"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Oltaszyn",
                            ParentId = new Guid("21db1b78-4a25-4f04-a6e3-31314bc45f94"),
                            PolishName = "Ołtaszyn"
                        },
                        new
                        {
                            Id = new Guid("968cb0ac-d6d7-41ac-9f92-2a88a4c5322e"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Powstancow-Slaskich",
                            ParentId = new Guid("21db1b78-4a25-4f04-a6e3-31314bc45f94"),
                            PolishName = "Powstańców Śląskich"
                        },
                        new
                        {
                            Id = new Guid("ddcc1be6-395e-43aa-ad72-a150b868f7f3"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Przedmiescie-Olawskie",
                            ParentId = new Guid("21db1b78-4a25-4f04-a6e3-31314bc45f94"),
                            PolishName = "Przedmieście Oławskie"
                        },
                        new
                        {
                            Id = new Guid("86c0e69c-1259-4245-b94f-9c33d12aa490"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Tarnogaj",
                            ParentId = new Guid("21db1b78-4a25-4f04-a6e3-31314bc45f94"),
                            PolishName = "Tarnogaj"
                        },
                        new
                        {
                            Id = new Guid("a63d5148-471b-422c-b016-0317c9689cd3"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Wojszyce",
                            ParentId = new Guid("21db1b78-4a25-4f04-a6e3-31314bc45f94"),
                            PolishName = "Wojszyce"
                        },
                        new
                        {
                            Id = new Guid("2fe676de-ebef-4e28-a012-61da79da6947"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Karlowice-Rozanka",
                            ParentId = new Guid("fc53428e-b09a-44fa-bff7-44379a6240ab"),
                            PolishName = "Karłowice-Różanka"
                        },
                        new
                        {
                            Id = new Guid("29b9a280-a2a5-4436-810c-78df10740360"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Kleczkow",
                            ParentId = new Guid("fc53428e-b09a-44fa-bff7-44379a6240ab"),
                            PolishName = "Kleczków"
                        },
                        new
                        {
                            Id = new Guid("ffe59d30-48ca-4534-a798-5406de30775d"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Kowale",
                            ParentId = new Guid("fc53428e-b09a-44fa-bff7-44379a6240ab"),
                            PolishName = "Kowale"
                        },
                        new
                        {
                            Id = new Guid("3b4ea3b0-cd9a-43a9-8af5-9636afaf82a1"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Lipa-Piotrowska",
                            ParentId = new Guid("fc53428e-b09a-44fa-bff7-44379a6240ab"),
                            PolishName = "Lipa Piotrowska"
                        },
                        new
                        {
                            Id = new Guid("7930362c-3810-43d6-a8a6-61f7bee04846"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Osobowice-Redzin",
                            ParentId = new Guid("fc53428e-b09a-44fa-bff7-44379a6240ab"),
                            PolishName = "Osobowice-Rędzin"
                        },
                        new
                        {
                            Id = new Guid("abe94cf7-c965-4223-b7df-be2b72f0fe28"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Pawlowice",
                            ParentId = new Guid("fc53428e-b09a-44fa-bff7-44379a6240ab"),
                            PolishName = "Pawłowice"
                        },
                        new
                        {
                            Id = new Guid("1c6699c2-d11f-41a1-bc25-69ec07279176"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Polanowice-Poswietne-Ligota",
                            ParentId = new Guid("fc53428e-b09a-44fa-bff7-44379a6240ab"),
                            PolishName = "Polanowice-Poświętne-Ligota"
                        },
                        new
                        {
                            Id = new Guid("1cd70b69-127f-4deb-a5cb-186c89a73861"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Psie-Pole-Zawidawie",
                            ParentId = new Guid("fc53428e-b09a-44fa-bff7-44379a6240ab"),
                            PolishName = "Psie Pole Zawidawie"
                        },
                        new
                        {
                            Id = new Guid("90c8dcff-3eda-4776-ba1e-fc505bcb89fd"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Soltysowice",
                            ParentId = new Guid("fc53428e-b09a-44fa-bff7-44379a6240ab"),
                            PolishName = "Sołtysowice"
                        },
                        new
                        {
                            Id = new Guid("33a46874-6ba2-46ab-a772-74f750a83f77"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Swojczyce-Strachocin-Wojnow",
                            ParentId = new Guid("fc53428e-b09a-44fa-bff7-44379a6240ab"),
                            PolishName = "Swojczyce-Strachocin-Wojnów"
                        },
                        new
                        {
                            Id = new Guid("2a5a62cf-051f-4270-a35b-8ec4a106c522"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Swiniary",
                            ParentId = new Guid("fc53428e-b09a-44fa-bff7-44379a6240ab"),
                            PolishName = "Świniary"
                        },
                        new
                        {
                            Id = new Guid("9446441a-79d3-4b14-949d-384ad704165d"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Widawa",
                            ParentId = new Guid("fc53428e-b09a-44fa-bff7-44379a6240ab"),
                            PolishName = "Widawa"
                        },
                        new
                        {
                            Id = new Guid("1d087abe-fee0-46b9-9212-c72d4bad5c0b"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Przedmiescie-Swidnickie",
                            ParentId = new Guid("0a098de4-92e4-4ef8-887a-141aaf11f8dc"),
                            PolishName = "Przedmieście Świdnickie"
                        },
                        new
                        {
                            Id = new Guid("ceb9a82f-0141-49ad-9927-8aeae16da244"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Szczepin",
                            ParentId = new Guid("0a098de4-92e4-4ef8-887a-141aaf11f8dc"),
                            PolishName = "Szczepin"
                        },
                        new
                        {
                            Id = new Guid("d83841fa-27fb-4f89-aab2-c40088f75980"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Biskupin-Sepolno-Dabie-Bartoszowice",
                            ParentId = new Guid("0a6a49ca-7508-49a8-bfae-3a995076943d"),
                            PolishName = "Biskupin-Sępolno-Dąbie-Bartoszowice"
                        },
                        new
                        {
                            Id = new Guid("6d9ed1ea-dda0-46c7-9649-4f18f682efda"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Nadodrze",
                            ParentId = new Guid("0a6a49ca-7508-49a8-bfae-3a995076943d"),
                            PolishName = "Nadodrze"
                        },
                        new
                        {
                            Id = new Guid("1c2ef079-52ef-4568-a06e-f882dcf28c23"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Olbin",
                            ParentId = new Guid("0a6a49ca-7508-49a8-bfae-3a995076943d"),
                            PolishName = "Ołbin"
                        },
                        new
                        {
                            Id = new Guid("918ce4d5-989f-4458-acc2-e00509b23a20"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Plac-Grunwaldzki",
                            ParentId = new Guid("0a6a49ca-7508-49a8-bfae-3a995076943d"),
                            PolishName = "Plac Grunwaldzki"
                        },
                        new
                        {
                            Id = new Guid("8932a433-c5b2-4c21-80ae-2f9e018f4a3e"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Zacisze-Zalesie-Szczytniki",
                            ParentId = new Guid("0a6a49ca-7508-49a8-bfae-3a995076943d"),
                            PolishName = "Zacisze-Zalesie-Szczytniki"
                        },
                        new
                        {
                            Id = new Guid("57de3b20-b1c7-4a77-96f7-9ce9c633ac7e"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Gadow-Maly",
                            ParentId = new Guid("e5e77c3d-bb85-4c7a-868e-43e5d6f623cc"),
                            PolishName = "Gądów Mały"
                        },
                        new
                        {
                            Id = new Guid("4b934a34-90af-43b0-b105-be7e72906468"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Popowice",
                            ParentId = new Guid("e5e77c3d-bb85-4c7a-868e-43e5d6f623cc"),
                            PolishName = "Popowice"
                        },
                        new
                        {
                            Id = new Guid("1f7169fa-0b63-473b-a47a-107073cefa8f"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Grabiszyn",
                            ParentId = new Guid("c75ff32f-6ee3-4347-86b4-1aa0a96651a7"),
                            PolishName = "Grabiszyn"
                        },
                        new
                        {
                            Id = new Guid("914214ae-cd23-4a67-8af6-0cf580813b6c"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Grabiszynek",
                            ParentId = new Guid("c75ff32f-6ee3-4347-86b4-1aa0a96651a7"),
                            PolishName = "Grabiszynek"
                        },
                        new
                        {
                            Id = new Guid("9b465ded-eed0-4ea4-9bf4-ebf3a642dd4b"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Jerzmanowo",
                            ParentId = new Guid("e3496408-fce3-4fee-b42b-3b0f529426e9"),
                            PolishName = "Jerzmanowo"
                        },
                        new
                        {
                            Id = new Guid("a1c44a64-da37-4dae-b099-0f952f259a56"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Jarnoltow",
                            ParentId = new Guid("e3496408-fce3-4fee-b42b-3b0f529426e9"),
                            PolishName = "Jarnołtów"
                        },
                        new
                        {
                            Id = new Guid("30fcd3fe-1733-49f6-b0ff-b58586454c86"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Strachowice",
                            ParentId = new Guid("e3496408-fce3-4fee-b42b-3b0f529426e9"),
                            PolishName = "Strachowice"
                        },
                        new
                        {
                            Id = new Guid("e660b554-5262-41bc-bf85-394fd6e281d0"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Osiniec",
                            ParentId = new Guid("e3496408-fce3-4fee-b42b-3b0f529426e9"),
                            PolishName = "Osiniec"
                        },
                        new
                        {
                            Id = new Guid("852cb711-daae-4cca-b65b-62283725e5da"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Stablowice",
                            ParentId = new Guid("c24e2403-5fc2-4e1a-bbf5-d4c510847742"),
                            PolishName = "Stabłowice"
                        },
                        new
                        {
                            Id = new Guid("6f8f3d9e-dcec-42f0-bec1-09a825cc3930"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Zlotniki",
                            ParentId = new Guid("c24e2403-5fc2-4e1a-bbf5-d4c510847742"),
                            PolishName = "Złotniki"
                        },
                        new
                        {
                            Id = new Guid("caceb67b-1738-459d-a8f7-a5482604bfdd"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Marszowice",
                            ParentId = new Guid("c24e2403-5fc2-4e1a-bbf5-d4c510847742"),
                            PolishName = "Marszowice"
                        },
                        new
                        {
                            Id = new Guid("4e7c7585-be5a-4d4d-a87b-0ec49f32fd4c"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Ratyn",
                            ParentId = new Guid("c24e2403-5fc2-4e1a-bbf5-d4c510847742"),
                            PolishName = "Ratyń"
                        },
                        new
                        {
                            Id = new Guid("ab96fd01-5a2d-4f2a-9b89-626b092ae4cb"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Mokra",
                            ParentId = new Guid("c24e2403-5fc2-4e1a-bbf5-d4c510847742"),
                            PolishName = "Mokra"
                        },
                        new
                        {
                            Id = new Guid("7dec37f3-d52d-477d-a292-ee1f617a6b3e"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Pustki",
                            ParentId = new Guid("c24e2403-5fc2-4e1a-bbf5-d4c510847742"),
                            PolishName = "Pustki"
                        },
                        new
                        {
                            Id = new Guid("93dd35eb-f541-4b84-9405-5bbe23c94f2d"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Zar",
                            ParentId = new Guid("c24e2403-5fc2-4e1a-bbf5-d4c510847742"),
                            PolishName = "Żar"
                        },
                        new
                        {
                            Id = new Guid("a4ce962e-5246-4952-80ae-0087f1266700"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Gajowa",
                            ParentId = new Guid("c24e2403-5fc2-4e1a-bbf5-d4c510847742"),
                            PolishName = "Gajowa"
                        },
                        new
                        {
                            Id = new Guid("4f2a852b-2c4c-44ca-b5ad-646221313c4c"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Pilczyce",
                            ParentId = new Guid("1019e1be-57d7-4ca6-9b38-f5da790eaa33"),
                            PolishName = "Pilczyce"
                        },
                        new
                        {
                            Id = new Guid("7ff08f6a-cfdb-40d2-b57f-0c96288b8d7a"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Kozanow",
                            ParentId = new Guid("1019e1be-57d7-4ca6-9b38-f5da790eaa33"),
                            PolishName = "Kozanów"
                        },
                        new
                        {
                            Id = new Guid("c91dc887-4deb-4274-abe3-be0baed37a33"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Popowice",
                            ParentId = new Guid("1019e1be-57d7-4ca6-9b38-f5da790eaa33"),
                            PolishName = "Popowice"
                        },
                        new
                        {
                            Id = new Guid("3a91b41d-5cf7-4480-bb5c-ed9179d7c00b"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Janowek",
                            ParentId = new Guid("e8858102-054a-4779-9760-7380ecf08df3"),
                            PolishName = "Janówek"
                        },
                        new
                        {
                            Id = new Guid("2b25ded6-a25f-441d-b8b8-53d7b7a8e255"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Nowa-Karczma",
                            ParentId = new Guid("e8858102-054a-4779-9760-7380ecf08df3"),
                            PolishName = "Nowa Karczma"
                        },
                        new
                        {
                            Id = new Guid("4d965d02-a05a-4c4b-a8c3-e9504b518185"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Glinianki",
                            ParentId = new Guid("88dd1ffd-00f4-469b-ae94-745e2a336ddb"),
                            PolishName = "Glinianki"
                        },
                        new
                        {
                            Id = new Guid("eff858bd-c899-4a2c-80ad-f6800ea0de14"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Partynice",
                            ParentId = new Guid("ac5d8893-9370-4546-bbb5-51edc01a442c"),
                            PolishName = "Partynice"
                        },
                        new
                        {
                            Id = new Guid("2615becf-bbc6-4ad6-b37b-68f1d3b9265d"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Ksieze-Male",
                            ParentId = new Guid("83bd3deb-0f48-4846-8eaf-54ade5b90915"),
                            PolishName = "Księże Małe"
                        },
                        new
                        {
                            Id = new Guid("b2669d90-3214-49f7-b17b-f974e3b8f22c"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Ksieze-Wielkie",
                            ParentId = new Guid("83bd3deb-0f48-4846-8eaf-54ade5b90915"),
                            PolishName = "Księże Wielkie"
                        },
                        new
                        {
                            Id = new Guid("cf8556b4-eaef-4eed-ba5e-98ce8eb3822b"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Swiatniki",
                            ParentId = new Guid("83bd3deb-0f48-4846-8eaf-54ade5b90915"),
                            PolishName = "Świątniki"
                        },
                        new
                        {
                            Id = new Guid("ba687519-0138-40e2-ac65-77d297c4955d"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Opatowice",
                            ParentId = new Guid("83bd3deb-0f48-4846-8eaf-54ade5b90915"),
                            PolishName = "Opatowice"
                        },
                        new
                        {
                            Id = new Guid("9cee8e4c-89bf-4cbc-8476-b130dabae470"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Bierdzany",
                            ParentId = new Guid("83bd3deb-0f48-4846-8eaf-54ade5b90915"),
                            PolishName = "Bierdzany"
                        },
                        new
                        {
                            Id = new Guid("d8abcb58-1ee0-45dc-bc44-633660d09d75"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Nowy-Dom",
                            ParentId = new Guid("83bd3deb-0f48-4846-8eaf-54ade5b90915"),
                            PolishName = "Nowy Dom"
                        },
                        new
                        {
                            Id = new Guid("af2687c8-b22b-4a50-9415-0d80a32dab06"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Poludnie",
                            ParentId = new Guid("968cb0ac-d6d7-41ac-9f92-2a88a4c5322e"),
                            PolishName = "Południe"
                        },
                        new
                        {
                            Id = new Guid("1c2dfb3d-1792-441c-976e-e958e007d9a3"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Dworek",
                            ParentId = new Guid("968cb0ac-d6d7-41ac-9f92-2a88a4c5322e"),
                            PolishName = "Dworek"
                        },
                        new
                        {
                            Id = new Guid("a042891b-3447-4381-b6d7-ba5918d16781"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Karlowice",
                            ParentId = new Guid("2fe676de-ebef-4e28-a012-61da79da6947"),
                            PolishName = "Karłowice"
                        },
                        new
                        {
                            Id = new Guid("96728063-86a3-44a9-b152-1f47a3319d28"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Rozanka",
                            ParentId = new Guid("2fe676de-ebef-4e28-a012-61da79da6947"),
                            PolishName = "Różanka"
                        },
                        new
                        {
                            Id = new Guid("288d3d2c-22d2-4553-80f1-fbda871f445c"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Mirowiec",
                            ParentId = new Guid("2fe676de-ebef-4e28-a012-61da79da6947"),
                            PolishName = "Mirowiec"
                        },
                        new
                        {
                            Id = new Guid("916e4be4-3b01-413d-ac4d-6ee95e5561e1"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Polanka",
                            ParentId = new Guid("2fe676de-ebef-4e28-a012-61da79da6947"),
                            PolishName = "Polanka"
                        },
                        new
                        {
                            Id = new Guid("62938578-400f-41b2-a1aa-f4b106a757b8"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Osobowice",
                            ParentId = new Guid("7930362c-3810-43d6-a8a6-61f7bee04846"),
                            PolishName = "Osobowice"
                        },
                        new
                        {
                            Id = new Guid("02639180-bbb6-4e94-9ac6-797e4992d537"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Redzin",
                            ParentId = new Guid("7930362c-3810-43d6-a8a6-61f7bee04846"),
                            PolishName = "Rędzin"
                        },
                        new
                        {
                            Id = new Guid("d0eeee0a-6b52-4d23-b089-23e87b2a2666"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Ligota",
                            ParentId = new Guid("1c6699c2-d11f-41a1-bc25-69ec07279176"),
                            PolishName = "Ligota"
                        },
                        new
                        {
                            Id = new Guid("7b46fbe5-b2e9-44b9-8744-761151fdb951"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Polanowice",
                            ParentId = new Guid("1c6699c2-d11f-41a1-bc25-69ec07279176"),
                            PolishName = "Polanowice"
                        },
                        new
                        {
                            Id = new Guid("036e6350-60cc-4663-b407-52eb10ad20dc"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Poswietne",
                            ParentId = new Guid("1c6699c2-d11f-41a1-bc25-69ec07279176"),
                            PolishName = "Poświętne"
                        },
                        new
                        {
                            Id = new Guid("fcad7d3e-c3cd-4887-8e55-bf81f38b7699"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Zakrzow",
                            ParentId = new Guid("1cd70b69-127f-4deb-a5cb-186c89a73861"),
                            PolishName = "Zakrzów"
                        },
                        new
                        {
                            Id = new Guid("911aac44-915c-4312-8480-231de7ca5140"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Zgorzelisko",
                            ParentId = new Guid("1cd70b69-127f-4deb-a5cb-186c89a73861"),
                            PolishName = "Zgorzelisko"
                        },
                        new
                        {
                            Id = new Guid("00f44bb0-0e67-4e1b-9458-ff6aecaa7e37"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Klokoczyce",
                            ParentId = new Guid("1cd70b69-127f-4deb-a5cb-186c89a73861"),
                            PolishName = "Kłokoczyce"
                        },
                        new
                        {
                            Id = new Guid("12fa45bb-787b-4b32-b435-eb5d5f2e8276"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Strachocin",
                            ParentId = new Guid("33a46874-6ba2-46ab-a772-74f750a83f77"),
                            PolishName = "Strachocin"
                        },
                        new
                        {
                            Id = new Guid("6b2513f1-c8c2-4bf3-b5de-7dbb43a8ab81"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Swojczyce",
                            ParentId = new Guid("33a46874-6ba2-46ab-a772-74f750a83f77"),
                            PolishName = "Swojczyce"
                        },
                        new
                        {
                            Id = new Guid("7ca1f8fc-fc80-4758-a884-c231d2d74934"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Wojnow",
                            ParentId = new Guid("33a46874-6ba2-46ab-a772-74f750a83f77"),
                            PolishName = "Wojnów"
                        },
                        new
                        {
                            Id = new Guid("74e43ed2-2357-4895-afbd-836cd2b9cc5e"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Popiele",
                            ParentId = new Guid("33a46874-6ba2-46ab-a772-74f750a83f77"),
                            PolishName = "Popiele"
                        },
                        new
                        {
                            Id = new Guid("830582c7-1783-4610-a6c1-804e6af3c2f8"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Bartoszowice",
                            ParentId = new Guid("d83841fa-27fb-4f89-aab2-c40088f75980"),
                            PolishName = "Bartoszowice"
                        },
                        new
                        {
                            Id = new Guid("b2244039-7b02-4221-bfa5-e58880238cdb"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Biskupin",
                            ParentId = new Guid("d83841fa-27fb-4f89-aab2-c40088f75980"),
                            PolishName = "Biskupin"
                        },
                        new
                        {
                            Id = new Guid("69838cb4-81f9-4e05-a50d-d224a039ce89"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Dabie",
                            ParentId = new Guid("d83841fa-27fb-4f89-aab2-c40088f75980"),
                            PolishName = "Dąbie"
                        },
                        new
                        {
                            Id = new Guid("c4de6e53-8b6e-45e1-a587-7fc5ae2ef8ac"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Sepolno",
                            ParentId = new Guid("d83841fa-27fb-4f89-aab2-c40088f75980"),
                            PolishName = "Sępolno"
                        },
                        new
                        {
                            Id = new Guid("c566fd0d-0873-4f6f-8b0a-070ea521dc93"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Szczytniki",
                            ParentId = new Guid("8932a433-c5b2-4c21-80ae-2f9e018f4a3e"),
                            PolishName = "Szczytniki"
                        },
                        new
                        {
                            Id = new Guid("4e9d230e-ce82-46c2-8024-0044e57e1c62"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Zacisze",
                            ParentId = new Guid("8932a433-c5b2-4c21-80ae-2f9e018f4a3e"),
                            PolishName = "Zacisze"
                        },
                        new
                        {
                            Id = new Guid("624bd6bd-e92c-4358-a021-269d791b7884"),
                            CityId = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Zalesie",
                            ParentId = new Guid("8932a433-c5b2-4c21-80ae-2f9e018f4a3e"),
                            PolishName = "Zalesie"
                        });
                });

            modelBuilder.Entity("Riva.AdministrativeDivisions.Infrastructure.DataAccess.RivaAdministrativeDivisionsSqlServer.Entities.CityDistrictNameVariantEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CityDistrictId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("CityDistrictId");

                    b.HasIndex("Value", "CityDistrictId")
                        .IsUnique();

                    b.ToTable("CityDistrictNameVariants");

                    b.HasData(
                        new
                        {
                            Id = new Guid("66d75b75-f425-49d2-87bd-bd109aca8a6d"),
                            CityDistrictId = new Guid("6dacf67a-ba5f-4bff-ac7f-95ed6fd4f889"),
                            Value = "Fabrycznej"
                        },
                        new
                        {
                            Id = new Guid("48ba02dc-da6d-4db3-a2b8-6838d658d1e2"),
                            CityDistrictId = new Guid("21db1b78-4a25-4f04-a6e3-31314bc45f94"),
                            Value = "Krzykach"
                        },
                        new
                        {
                            Id = new Guid("d1c5265d-4c56-448a-bdbd-434ab0b105c0"),
                            CityDistrictId = new Guid("fc53428e-b09a-44fa-bff7-44379a6240ab"),
                            Value = "Psim polu"
                        },
                        new
                        {
                            Id = new Guid("2818fd91-86cc-44ab-91e9-72e90449457f"),
                            CityDistrictId = new Guid("0a098de4-92e4-4ef8-887a-141aaf11f8dc"),
                            Value = "Starym miescie"
                        },
                        new
                        {
                            Id = new Guid("e39a663c-5144-4ed7-a56a-dfe6569a3362"),
                            CityDistrictId = new Guid("0a098de4-92e4-4ef8-887a-141aaf11f8dc"),
                            Value = "Starym mieście"
                        },
                        new
                        {
                            Id = new Guid("0506708d-1928-47d9-84ac-cae51292069c"),
                            CityDistrictId = new Guid("0a6a49ca-7508-49a8-bfae-3a995076943d"),
                            Value = "Srodmiesciu"
                        },
                        new
                        {
                            Id = new Guid("13f00177-c102-452e-a400-dff52e62960e"),
                            CityDistrictId = new Guid("0a6a49ca-7508-49a8-bfae-3a995076943d"),
                            Value = "Śródmieściu"
                        },
                        new
                        {
                            Id = new Guid("c1508b6a-185b-4220-84b6-e2a2e6a20a44"),
                            CityDistrictId = new Guid("882cc824-1d0b-4acd-89d0-c846b98ab946"),
                            Value = "Gajowicach"
                        },
                        new
                        {
                            Id = new Guid("9887aa49-d6ba-4ae8-9a02-a68ed4adfaae"),
                            CityDistrictId = new Guid("f6c8b915-38cd-44d8-878d-115cc440c5d3"),
                            Value = "Kuznikach"
                        },
                        new
                        {
                            Id = new Guid("6664771d-f04c-49a6-8f17-99942bd7ca88"),
                            CityDistrictId = new Guid("f6c8b915-38cd-44d8-878d-115cc440c5d3"),
                            Value = "Kuźnikach"
                        },
                        new
                        {
                            Id = new Guid("8143a298-10ad-4930-8cb3-ca56b1f648c0"),
                            CityDistrictId = new Guid("c24e2403-5fc2-4e1a-bbf5-d4c510847742"),
                            Value = "Lesnicy"
                        },
                        new
                        {
                            Id = new Guid("00647eee-a5a5-4756-81d8-fa1747055e98"),
                            CityDistrictId = new Guid("c24e2403-5fc2-4e1a-bbf5-d4c510847742"),
                            Value = "Leśnicy"
                        },
                        new
                        {
                            Id = new Guid("0b7bee7e-61d6-457e-9553-3640b3bd86c3"),
                            CityDistrictId = new Guid("4a7cfa64-3c42-46d7-b694-f6b8eccb5ab6"),
                            Value = "Maslicach"
                        },
                        new
                        {
                            Id = new Guid("031211be-eb65-4e62-8c8c-e457dcaf014e"),
                            CityDistrictId = new Guid("4a7cfa64-3c42-46d7-b694-f6b8eccb5ab6"),
                            Value = "Maślicach"
                        },
                        new
                        {
                            Id = new Guid("06d32d31-64fa-4df1-9817-67fbc7686775"),
                            CityDistrictId = new Guid("a45a6df5-4695-4db2-a362-c0477eab1c8b"),
                            Value = "Muchobor"
                        },
                        new
                        {
                            Id = new Guid("69b7af3b-0993-4d4b-9cfc-5081c80fd9bc"),
                            CityDistrictId = new Guid("a45a6df5-4695-4db2-a362-c0477eab1c8b"),
                            Value = "Muchobór"
                        },
                        new
                        {
                            Id = new Guid("e10eec4e-d540-4fd5-b278-e57d3d39feeb"),
                            CityDistrictId = new Guid("96adb77d-8505-46fc-9515-41fee1f06a6a"),
                            Value = "Muchobor"
                        },
                        new
                        {
                            Id = new Guid("a3dbdf7a-dec2-4a7b-892b-0853a5fde42b"),
                            CityDistrictId = new Guid("96adb77d-8505-46fc-9515-41fee1f06a6a"),
                            Value = "Muchobór"
                        },
                        new
                        {
                            Id = new Guid("36876439-f286-42d9-8eba-857629dcee60"),
                            CityDistrictId = new Guid("aa5f1748-d858-45c6-b1bd-fd68d98c8b38"),
                            Value = "Nowym dworze"
                        },
                        new
                        {
                            Id = new Guid("cae1802d-4284-436b-a596-4b7d8a21545d"),
                            CityDistrictId = new Guid("aa5f1748-d858-45c6-b1bd-fd68d98c8b38"),
                            Value = "Nowy dwor"
                        },
                        new
                        {
                            Id = new Guid("36f80b74-e20d-4259-858a-f2b93968e225"),
                            CityDistrictId = new Guid("e8858102-054a-4779-9760-7380ecf08df3"),
                            Value = "Praczu Odrzanskim"
                        },
                        new
                        {
                            Id = new Guid("79f208ef-ad26-4d97-b5ed-b8fb27af6d70"),
                            CityDistrictId = new Guid("e8858102-054a-4779-9760-7380ecf08df3"),
                            Value = "Praczu Odrzańskim"
                        },
                        new
                        {
                            Id = new Guid("14bf2192-8222-41bd-830f-edcd5dc1cd2f"),
                            CityDistrictId = new Guid("7dea11fb-65ed-4b98-a06c-cfd01917b655"),
                            Value = "Zernikach"
                        },
                        new
                        {
                            Id = new Guid("5566cab4-b65c-4e46-9f79-ec340c3d4912"),
                            CityDistrictId = new Guid("7dea11fb-65ed-4b98-a06c-cfd01917b655"),
                            Value = "Żernikach"
                        },
                        new
                        {
                            Id = new Guid("de46a69d-06c5-450c-8897-f7f4caf216ca"),
                            CityDistrictId = new Guid("853f916a-3fbd-4baf-8a09-f29eee498966"),
                            Value = "Bienkowicach"
                        },
                        new
                        {
                            Id = new Guid("d91def1f-d742-46b6-bf5d-d4a69eb5854d"),
                            CityDistrictId = new Guid("853f916a-3fbd-4baf-8a09-f29eee498966"),
                            Value = "Bieńkowicach"
                        },
                        new
                        {
                            Id = new Guid("0aaa7369-4cbc-4dfc-b5fb-49a5da711793"),
                            CityDistrictId = new Guid("7f7e9487-cb8d-489b-8a58-827756622895"),
                            Value = "Borku"
                        },
                        new
                        {
                            Id = new Guid("74cbad72-cc4d-49ca-bb38-2dc5e3cb63ac"),
                            CityDistrictId = new Guid("88dd1ffd-00f4-469b-ae94-745e2a336ddb"),
                            Value = "Hubach"
                        },
                        new
                        {
                            Id = new Guid("e1e41732-480f-4b65-b3c1-18a71de09ec1"),
                            CityDistrictId = new Guid("0a77f641-5227-4f4e-8f89-91d431218daa"),
                            Value = "Jagodnie"
                        },
                        new
                        {
                            Id = new Guid("5b0c2ff8-1492-4fb6-97ea-ba9d0b502ff5"),
                            CityDistrictId = new Guid("59a2d9a7-e6dd-4b8e-b1e7-47e88f18e0dc"),
                            Value = "Klecinie"
                        },
                        new
                        {
                            Id = new Guid("f2b3de61-5df5-477f-ad14-b3e0e11a1adc"),
                            CityDistrictId = new Guid("83bd3deb-0f48-4846-8eaf-54ade5b90915"),
                            Value = "Ksiezach"
                        },
                        new
                        {
                            Id = new Guid("f97797c4-93a3-4793-9fb6-d909de3d7d30"),
                            CityDistrictId = new Guid("83bd3deb-0f48-4846-8eaf-54ade5b90915"),
                            Value = "Księżach"
                        },
                        new
                        {
                            Id = new Guid("fcc80916-8945-4b95-9217-566da6904d49"),
                            CityDistrictId = new Guid("968cb0ac-d6d7-41ac-9f92-2a88a4c5322e"),
                            Value = "Powstancow slaskich"
                        },
                        new
                        {
                            Id = new Guid("398c9bd5-dd85-438c-9715-107372d2f301"),
                            CityDistrictId = new Guid("968cb0ac-d6d7-41ac-9f92-2a88a4c5322e"),
                            Value = "Przedmiesciu olawskim"
                        },
                        new
                        {
                            Id = new Guid("75b9425a-4be8-4353-b9c3-9562454e56a2"),
                            CityDistrictId = new Guid("ddcc1be6-395e-43aa-ad72-a150b868f7f3"),
                            Value = "Przedmieściu oławskim"
                        },
                        new
                        {
                            Id = new Guid("8d1c7a31-1459-42ff-a056-8ef428f9eacf"),
                            CityDistrictId = new Guid("a63d5148-471b-422c-b016-0317c9689cd3"),
                            Value = "Wojszycach"
                        },
                        new
                        {
                            Id = new Guid("adc28067-787f-4b88-9aa4-f613a503237d"),
                            CityDistrictId = new Guid("ffe59d30-48ca-4534-a798-5406de30775d"),
                            Value = "Kowalach"
                        },
                        new
                        {
                            Id = new Guid("8553f3fb-8859-4299-b0cc-a4dc8b38af51"),
                            CityDistrictId = new Guid("3b4ea3b0-cd9a-43a9-8af5-9636afaf82a1"),
                            Value = "Lipie piotrowskiej"
                        },
                        new
                        {
                            Id = new Guid("2fe7c271-1988-436e-bd5e-c3caaaa28155"),
                            CityDistrictId = new Guid("abe94cf7-c965-4223-b7df-be2b72f0fe28"),
                            Value = "Pawlowicach"
                        },
                        new
                        {
                            Id = new Guid("07e84e5a-3a55-4c12-a880-5bd56427c725"),
                            CityDistrictId = new Guid("abe94cf7-c965-4223-b7df-be2b72f0fe28"),
                            Value = "Pawłowicach"
                        },
                        new
                        {
                            Id = new Guid("1a40665c-9f74-4082-ab12-37cf1159a17c"),
                            CityDistrictId = new Guid("90c8dcff-3eda-4776-ba1e-fc505bcb89fd"),
                            Value = "Soltysowicach"
                        },
                        new
                        {
                            Id = new Guid("c50193a4-a54b-4d14-8187-6b748b436818"),
                            CityDistrictId = new Guid("90c8dcff-3eda-4776-ba1e-fc505bcb89fd"),
                            Value = "Sołtysowicach"
                        },
                        new
                        {
                            Id = new Guid("bf4a74ab-550c-4ecb-9ba7-40faf3fce1e2"),
                            CityDistrictId = new Guid("2a5a62cf-051f-4270-a35b-8ec4a106c522"),
                            Value = "Swiniarach"
                        },
                        new
                        {
                            Id = new Guid("1362264a-2684-493c-8115-79a400c3454f"),
                            CityDistrictId = new Guid("2a5a62cf-051f-4270-a35b-8ec4a106c522"),
                            Value = "Świniarach"
                        },
                        new
                        {
                            Id = new Guid("33e50a7d-a7b4-4941-8c25-c922639b007d"),
                            CityDistrictId = new Guid("9446441a-79d3-4b14-949d-384ad704165d"),
                            Value = "Widawie"
                        },
                        new
                        {
                            Id = new Guid("9d672522-5fdf-42c1-b1e2-564d76975d3a"),
                            CityDistrictId = new Guid("1d087abe-fee0-46b9-9212-c72d4bad5c0b"),
                            Value = "Przedmiesciu swidnickim"
                        },
                        new
                        {
                            Id = new Guid("038c7e67-924c-4eae-9ed7-ad6e4aa5f77d"),
                            CityDistrictId = new Guid("1d087abe-fee0-46b9-9212-c72d4bad5c0b"),
                            Value = "Przedmieściu świdnickim"
                        },
                        new
                        {
                            Id = new Guid("f08a8949-ac74-41ca-bf74-ce62f3b5c684"),
                            CityDistrictId = new Guid("6d9ed1ea-dda0-46c7-9649-4f18f682efda"),
                            Value = "Nadodrzu"
                        },
                        new
                        {
                            Id = new Guid("f70d50cd-f0f9-40c1-8417-c895ae78d0dd"),
                            CityDistrictId = new Guid("918ce4d5-989f-4458-acc2-e00509b23a20"),
                            Value = "Placu grunwaldzkim"
                        },
                        new
                        {
                            Id = new Guid("ce9dc855-4083-467e-98fa-45d5b8067bee"),
                            CityDistrictId = new Guid("57de3b20-b1c7-4a77-96f7-9ce9c633ac7e"),
                            Value = "Gadowie malym"
                        },
                        new
                        {
                            Id = new Guid("fd6f22bc-a510-4795-b02f-2b33ffa84bd1"),
                            CityDistrictId = new Guid("57de3b20-b1c7-4a77-96f7-9ce9c633ac7e"),
                            Value = "Gadowie małym"
                        },
                        new
                        {
                            Id = new Guid("fa2ab82d-7261-4d49-b05e-8164018bdb09"),
                            CityDistrictId = new Guid("57de3b20-b1c7-4a77-96f7-9ce9c633ac7e"),
                            Value = "Gadowie"
                        },
                        new
                        {
                            Id = new Guid("555faae5-c3ea-46c2-a312-3828b0cd05cf"),
                            CityDistrictId = new Guid("57de3b20-b1c7-4a77-96f7-9ce9c633ac7e"),
                            Value = "Gądowie"
                        },
                        new
                        {
                            Id = new Guid("102375d5-bad8-424e-ab9d-78bc8a03de5e"),
                            CityDistrictId = new Guid("4b934a34-90af-43b0-b105-be7e72906468"),
                            Value = "Popowicach"
                        },
                        new
                        {
                            Id = new Guid("c97df31e-3a4e-4489-94b5-18cf7fe09b34"),
                            CityDistrictId = new Guid("1f7169fa-0b63-473b-a47a-107073cefa8f"),
                            Value = "Grabiszynie"
                        },
                        new
                        {
                            Id = new Guid("3d306915-b766-420a-8993-82bbb779718d"),
                            CityDistrictId = new Guid("914214ae-cd23-4a67-8af6-0cf580813b6c"),
                            Value = "Grabiszynku"
                        },
                        new
                        {
                            Id = new Guid("8dc8b068-bb87-4b46-809b-a45781f58f96"),
                            CityDistrictId = new Guid("9b465ded-eed0-4ea4-9bf4-ebf3a642dd4b"),
                            Value = "Jerzmanowej"
                        },
                        new
                        {
                            Id = new Guid("4d4a90d6-773b-4e84-a0f6-07f55cff2f61"),
                            CityDistrictId = new Guid("a1c44a64-da37-4dae-b099-0f952f259a56"),
                            Value = "Jarnoltowku"
                        },
                        new
                        {
                            Id = new Guid("a9d5e393-27d8-4d24-b008-30470d46535e"),
                            CityDistrictId = new Guid("a1c44a64-da37-4dae-b099-0f952f259a56"),
                            Value = "Jarnołtówku"
                        },
                        new
                        {
                            Id = new Guid("c59474af-af99-4ce2-8ee1-8b0dbf3eb1f0"),
                            CityDistrictId = new Guid("30fcd3fe-1733-49f6-b0ff-b58586454c86"),
                            Value = "Strachowicach"
                        },
                        new
                        {
                            Id = new Guid("95b5989f-8a0f-4b19-912b-b024b9c919d3"),
                            CityDistrictId = new Guid("e660b554-5262-41bc-bf85-394fd6e281d0"),
                            Value = "Osincu"
                        },
                        new
                        {
                            Id = new Guid("a5786af0-e2fd-4799-a008-0f15f512b66d"),
                            CityDistrictId = new Guid("e660b554-5262-41bc-bf85-394fd6e281d0"),
                            Value = "Osińcu"
                        },
                        new
                        {
                            Id = new Guid("e49553df-fd18-4191-8a81-4507163bb5d8"),
                            CityDistrictId = new Guid("852cb711-daae-4cca-b65b-62283725e5da"),
                            Value = "Stablowicach"
                        },
                        new
                        {
                            Id = new Guid("e8da6925-f255-478f-b819-9868a547c995"),
                            CityDistrictId = new Guid("852cb711-daae-4cca-b65b-62283725e5da"),
                            Value = "Stabłowicach"
                        },
                        new
                        {
                            Id = new Guid("24a63bab-fad8-4bf8-a597-cf42be71ac22"),
                            CityDistrictId = new Guid("6f8f3d9e-dcec-42f0-bec1-09a825cc3930"),
                            Value = "Zlotnikach"
                        },
                        new
                        {
                            Id = new Guid("beafde37-3210-4660-9741-521e82b1783b"),
                            CityDistrictId = new Guid("6f8f3d9e-dcec-42f0-bec1-09a825cc3930"),
                            Value = "Złotnikach"
                        },
                        new
                        {
                            Id = new Guid("957868bc-3233-453b-a543-768889c19e95"),
                            CityDistrictId = new Guid("caceb67b-1738-459d-a8f7-a5482604bfdd"),
                            Value = "Marszowicach"
                        },
                        new
                        {
                            Id = new Guid("cec42b5e-3948-454d-92e4-449fcc02cf1e"),
                            CityDistrictId = new Guid("4e7c7585-be5a-4d4d-a87b-0ec49f32fd4c"),
                            Value = "Ratuniu"
                        },
                        new
                        {
                            Id = new Guid("8862266f-3ab4-4d52-b37a-27a59f9d99f7"),
                            CityDistrictId = new Guid("ab96fd01-5a2d-4f2a-9b89-626b092ae4cb"),
                            Value = "Mokrej"
                        },
                        new
                        {
                            Id = new Guid("0b8cff6a-ebc7-4ced-a7b5-fa4ae46df7d3"),
                            CityDistrictId = new Guid("7dec37f3-d52d-477d-a292-ee1f617a6b3e"),
                            Value = "Pustkach"
                        },
                        new
                        {
                            Id = new Guid("613ea767-69f2-47db-bbe9-4e6b5387587d"),
                            CityDistrictId = new Guid("a4ce962e-5246-4952-80ae-0087f1266700"),
                            Value = "Gajowej"
                        },
                        new
                        {
                            Id = new Guid("0a8d4b73-65dc-4b62-b350-d738bf4e7f19"),
                            CityDistrictId = new Guid("4f2a852b-2c4c-44ca-b5ad-646221313c4c"),
                            Value = "Pilczycach"
                        },
                        new
                        {
                            Id = new Guid("a424b69a-e8c3-47ac-ac7e-4e72a47d8471"),
                            CityDistrictId = new Guid("c91dc887-4deb-4274-abe3-be0baed37a33"),
                            Value = "Popowicach"
                        },
                        new
                        {
                            Id = new Guid("45dfb37b-fbb4-4e5d-87b6-fed3935319d2"),
                            CityDistrictId = new Guid("3a91b41d-5cf7-4480-bb5c-ed9179d7c00b"),
                            Value = "Janowku"
                        },
                        new
                        {
                            Id = new Guid("87e02521-d428-4e7c-804f-cd0dfa08aa34"),
                            CityDistrictId = new Guid("3a91b41d-5cf7-4480-bb5c-ed9179d7c00b"),
                            Value = "Janówku"
                        },
                        new
                        {
                            Id = new Guid("6d5ce240-f42a-464c-937e-b5f20551ceea"),
                            CityDistrictId = new Guid("2b25ded6-a25f-441d-b8b8-53d7b7a8e255"),
                            Value = "Nowej karczmie"
                        },
                        new
                        {
                            Id = new Guid("a2100738-eb14-47e0-9196-cb69461412e7"),
                            CityDistrictId = new Guid("4d965d02-a05a-4c4b-a8c3-e9504b518185"),
                            Value = "Gliniankach"
                        },
                        new
                        {
                            Id = new Guid("22b24ff3-3f3c-438e-a1a9-cf3eded4650a"),
                            CityDistrictId = new Guid("eff858bd-c899-4a2c-80ad-f6800ea0de14"),
                            Value = "Partynicach"
                        },
                        new
                        {
                            Id = new Guid("0a0421bd-f92e-40ec-aa81-654d9c796e38"),
                            CityDistrictId = new Guid("2615becf-bbc6-4ad6-b37b-68f1d3b9265d"),
                            Value = "Ksiezach malych"
                        },
                        new
                        {
                            Id = new Guid("555cb670-935c-4bbd-b773-5f25271103ec"),
                            CityDistrictId = new Guid("2615becf-bbc6-4ad6-b37b-68f1d3b9265d"),
                            Value = "Księżach małych"
                        },
                        new
                        {
                            Id = new Guid("4fbfa51b-c049-45fd-88e8-45fd03cdd819"),
                            CityDistrictId = new Guid("2615becf-bbc6-4ad6-b37b-68f1d3b9265d"),
                            Value = "Ksiezach"
                        },
                        new
                        {
                            Id = new Guid("0fba6ccd-b37a-4359-a94c-c169b8b2af8d"),
                            CityDistrictId = new Guid("2615becf-bbc6-4ad6-b37b-68f1d3b9265d"),
                            Value = "Księżach"
                        },
                        new
                        {
                            Id = new Guid("b3d999b4-1031-48bf-9b77-847615bad75a"),
                            CityDistrictId = new Guid("b2669d90-3214-49f7-b17b-f974e3b8f22c"),
                            Value = "Ksiezach wielkich"
                        },
                        new
                        {
                            Id = new Guid("0f938c04-e8bf-4af2-9895-608c90a11286"),
                            CityDistrictId = new Guid("b2669d90-3214-49f7-b17b-f974e3b8f22c"),
                            Value = "Księżach wielkich"
                        },
                        new
                        {
                            Id = new Guid("7f35c1d1-e12a-4f78-b976-adfc3efb10c2"),
                            CityDistrictId = new Guid("b2669d90-3214-49f7-b17b-f974e3b8f22c"),
                            Value = "Ksiezach"
                        },
                        new
                        {
                            Id = new Guid("2aa68cd4-36aa-430f-b48d-cb147627c401"),
                            CityDistrictId = new Guid("b2669d90-3214-49f7-b17b-f974e3b8f22c"),
                            Value = "Księżach"
                        },
                        new
                        {
                            Id = new Guid("ee076fa3-7401-418e-9fe0-a22d16953535"),
                            CityDistrictId = new Guid("cf8556b4-eaef-4eed-ba5e-98ce8eb3822b"),
                            Value = "Swiatnikach"
                        },
                        new
                        {
                            Id = new Guid("12346d4c-6726-4531-a24f-ddfbef4abcc3"),
                            CityDistrictId = new Guid("cf8556b4-eaef-4eed-ba5e-98ce8eb3822b"),
                            Value = "Świątnikach"
                        },
                        new
                        {
                            Id = new Guid("5cc8a418-24b3-48ea-9438-b7c51818b84f"),
                            CityDistrictId = new Guid("ba687519-0138-40e2-ac65-77d297c4955d"),
                            Value = "Opatowicach"
                        },
                        new
                        {
                            Id = new Guid("19b50d37-d315-45cc-873f-d6b0e7d51c59"),
                            CityDistrictId = new Guid("9cee8e4c-89bf-4cbc-8476-b130dabae470"),
                            Value = "Bierdzanach"
                        },
                        new
                        {
                            Id = new Guid("0651439c-bf20-45d2-9ceb-ee5860a036cd"),
                            CityDistrictId = new Guid("d8abcb58-1ee0-45dc-bc44-633660d09d75"),
                            Value = "Nowym domie"
                        },
                        new
                        {
                            Id = new Guid("fa14c562-e3c8-4a0f-ac77-2b54c7a9567f"),
                            CityDistrictId = new Guid("af2687c8-b22b-4a50-9415-0d80a32dab06"),
                            Value = "Poludniu"
                        },
                        new
                        {
                            Id = new Guid("27ca7cbe-07c4-46f8-b6a3-9c6583121c0e"),
                            CityDistrictId = new Guid("af2687c8-b22b-4a50-9415-0d80a32dab06"),
                            Value = "Południu"
                        },
                        new
                        {
                            Id = new Guid("d210a28a-04ac-4f90-9697-955048e215a9"),
                            CityDistrictId = new Guid("1c2dfb3d-1792-441c-976e-e958e007d9a3"),
                            Value = "Dworku"
                        },
                        new
                        {
                            Id = new Guid("b75d510f-974f-46c9-a8e5-263deb2ec7f9"),
                            CityDistrictId = new Guid("a042891b-3447-4381-b6d7-ba5918d16781"),
                            Value = "Karlowicach"
                        },
                        new
                        {
                            Id = new Guid("c7024bc0-706e-4207-8ed3-458b6ae0a5b0"),
                            CityDistrictId = new Guid("a042891b-3447-4381-b6d7-ba5918d16781"),
                            Value = "Karłowicach"
                        },
                        new
                        {
                            Id = new Guid("cef3a3e1-7b49-42a6-89ad-a63b35e4cb24"),
                            CityDistrictId = new Guid("96728063-86a3-44a9-b152-1f47a3319d28"),
                            Value = "Rozance"
                        },
                        new
                        {
                            Id = new Guid("8de4117c-6c9e-4ff8-a207-ae26e8a98b47"),
                            CityDistrictId = new Guid("96728063-86a3-44a9-b152-1f47a3319d28"),
                            Value = "Różance"
                        },
                        new
                        {
                            Id = new Guid("4183882f-72ca-4d0c-a28e-eaede21d9ea3"),
                            CityDistrictId = new Guid("288d3d2c-22d2-4553-80f1-fbda871f445c"),
                            Value = "Mirowcu"
                        },
                        new
                        {
                            Id = new Guid("a828a718-9827-47f2-bd1e-9bd7df8b03a5"),
                            CityDistrictId = new Guid("916e4be4-3b01-413d-ac4d-6ee95e5561e1"),
                            Value = "Polance"
                        },
                        new
                        {
                            Id = new Guid("c9d79cef-309e-422a-825f-cf1a02f8e31d"),
                            CityDistrictId = new Guid("d0eeee0a-6b52-4d23-b089-23e87b2a2666"),
                            Value = "Ligocie"
                        },
                        new
                        {
                            Id = new Guid("12a9bc9a-4207-4d0e-b1db-967050d4cdd7"),
                            CityDistrictId = new Guid("7b46fbe5-b2e9-44b9-8744-761151fdb951"),
                            Value = "Polanowicach"
                        },
                        new
                        {
                            Id = new Guid("40ac09e2-cf6b-409f-b615-0e9436ae298d"),
                            CityDistrictId = new Guid("036e6350-60cc-4663-b407-52eb10ad20dc"),
                            Value = "Poswietnym"
                        },
                        new
                        {
                            Id = new Guid("841c651c-fb9a-401e-815f-cd6ab7bca735"),
                            CityDistrictId = new Guid("036e6350-60cc-4663-b407-52eb10ad20dc"),
                            Value = "Poświętnym"
                        },
                        new
                        {
                            Id = new Guid("5bf332e3-2d61-485b-8bb4-d7f8e3f94fc3"),
                            CityDistrictId = new Guid("036e6350-60cc-4663-b407-52eb10ad20dc"),
                            Value = "Poswietnej"
                        },
                        new
                        {
                            Id = new Guid("b8223315-487f-42dd-a0e4-079f8a9f9ed5"),
                            CityDistrictId = new Guid("036e6350-60cc-4663-b407-52eb10ad20dc"),
                            Value = "Poświętnej"
                        },
                        new
                        {
                            Id = new Guid("720e49e0-7d45-4b31-9cbd-ee99ea23944e"),
                            CityDistrictId = new Guid("fcad7d3e-c3cd-4887-8e55-bf81f38b7699"),
                            Value = "Zakrzowie"
                        },
                        new
                        {
                            Id = new Guid("18a0f2a3-4a9f-4d9c-8e54-a468f73e3016"),
                            CityDistrictId = new Guid("911aac44-915c-4312-8480-231de7ca5140"),
                            Value = "Zgorzelisku"
                        },
                        new
                        {
                            Id = new Guid("1b49dee5-b31f-42a4-b684-4ff375852958"),
                            CityDistrictId = new Guid("00f44bb0-0e67-4e1b-9458-ff6aecaa7e37"),
                            Value = "Klokoczycach"
                        },
                        new
                        {
                            Id = new Guid("66beb497-5b50-4555-b506-6da578d529cc"),
                            CityDistrictId = new Guid("00f44bb0-0e67-4e1b-9458-ff6aecaa7e37"),
                            Value = "Kłokoczycach"
                        },
                        new
                        {
                            Id = new Guid("c9105703-487c-4ac0-879f-f6c7f83c1274"),
                            CityDistrictId = new Guid("6b2513f1-c8c2-4bf3-b5de-7dbb43a8ab81"),
                            Value = "Swojszycach"
                        },
                        new
                        {
                            Id = new Guid("55e05adc-8f32-405d-810e-196eb539cd6a"),
                            CityDistrictId = new Guid("7ca1f8fc-fc80-4758-a884-c231d2d74934"),
                            Value = "Wojnowie"
                        },
                        new
                        {
                            Id = new Guid("1152ab6d-77ad-4923-9712-d56d4c0c307d"),
                            CityDistrictId = new Guid("74e43ed2-2357-4895-afbd-836cd2b9cc5e"),
                            Value = "Popielach"
                        },
                        new
                        {
                            Id = new Guid("e31e1cd0-f62b-495c-a51f-6d1afaeff0d5"),
                            CityDistrictId = new Guid("830582c7-1783-4610-a6c1-804e6af3c2f8"),
                            Value = "Bartoszowicach"
                        },
                        new
                        {
                            Id = new Guid("2492d889-2847-4e9e-8983-d88e2ae9a388"),
                            CityDistrictId = new Guid("69838cb4-81f9-4e05-a50d-d224a039ce89"),
                            Value = "Dabiach"
                        },
                        new
                        {
                            Id = new Guid("cc7060d7-6402-4211-887c-d774c2880534"),
                            CityDistrictId = new Guid("69838cb4-81f9-4e05-a50d-d224a039ce89"),
                            Value = "Dąbiach"
                        },
                        new
                        {
                            Id = new Guid("76c5dafb-9e64-4bd1-84f3-afd77f63a394"),
                            CityDistrictId = new Guid("69838cb4-81f9-4e05-a50d-d224a039ce89"),
                            Value = "Dabiu"
                        },
                        new
                        {
                            Id = new Guid("1245afd8-097f-4270-b123-cd6c49c4b005"),
                            CityDistrictId = new Guid("69838cb4-81f9-4e05-a50d-d224a039ce89"),
                            Value = "Dąbiu"
                        },
                        new
                        {
                            Id = new Guid("af49739d-41ae-4c00-a285-5ebea27c1580"),
                            CityDistrictId = new Guid("c4de6e53-8b6e-45e1-a587-7fc5ae2ef8ac"),
                            Value = "Sepolnie"
                        },
                        new
                        {
                            Id = new Guid("9d4f921e-d7e2-4850-9130-9755688c17cf"),
                            CityDistrictId = new Guid("c4de6e53-8b6e-45e1-a587-7fc5ae2ef8ac"),
                            Value = "Sępolnie"
                        },
                        new
                        {
                            Id = new Guid("efae3434-18c0-4522-8e73-78af7e558156"),
                            CityDistrictId = new Guid("c566fd0d-0873-4f6f-8b0a-070ea521dc93"),
                            Value = "Szczytnikach"
                        },
                        new
                        {
                            Id = new Guid("8d09ca52-81f3-4081-a9a6-b0a38f061054"),
                            CityDistrictId = new Guid("4e9d230e-ce82-46c2-8024-0044e57e1c62"),
                            Value = "Zaciszu"
                        },
                        new
                        {
                            Id = new Guid("68524e8d-dac4-449d-bab5-587ce356b222"),
                            CityDistrictId = new Guid("624bd6bd-e92c-4358-a021-269d791b7884"),
                            Value = "Zalesiu"
                        });
                });

            modelBuilder.Entity("Riva.AdministrativeDivisions.Infrastructure.DataAccess.RivaAdministrativeDivisionsSqlServer.Entities.CityEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PolishName")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("StateId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.HasIndex("Name", "StateId")
                        .IsUnique();

                    b.HasIndex("PolishName", "StateId")
                        .IsUnique();

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1d02ce58-3bfe-46bc-aa61-d2de1c1690c1"),
                            Name = "Wroclaw",
                            PolishName = "Wrocław",
                            StateId = new Guid("23cbd1a9-78b5-4b7f-82f8-510e792d6022")
                        });
                });

            modelBuilder.Entity("Riva.AdministrativeDivisions.Infrastructure.DataAccess.RivaAdministrativeDivisionsSqlServer.Entities.StateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PolishName")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("PolishName")
                        .IsUnique();

                    b.ToTable("States");

                    b.HasData(
                        new
                        {
                            Id = new Guid("23cbd1a9-78b5-4b7f-82f8-510e792d6022"),
                            Name = "Dolnoslaskie",
                            PolishName = "Dolnośląskie"
                        },
                        new
                        {
                            Id = new Guid("0b2d0ba0-0365-4d6a-a2bf-f05a9fd08871"),
                            Name = "Kujawsko-pomorskie",
                            PolishName = "Kujawsko-pomorskie"
                        },
                        new
                        {
                            Id = new Guid("9d2640f7-266e-4274-9f42-a9cd14aa41e1"),
                            Name = "Lubelskie",
                            PolishName = "Lubelskie"
                        },
                        new
                        {
                            Id = new Guid("c2c3864c-7d24-4f26-a286-9e859352e231"),
                            Name = "Lubuskie",
                            PolishName = "Lubuskie"
                        },
                        new
                        {
                            Id = new Guid("b2d6b891-65a3-4b8e-8a15-f80b335d4e1a"),
                            Name = "Lodzkie",
                            PolishName = "Łódzkie"
                        },
                        new
                        {
                            Id = new Guid("f5168cc9-f98d-4a4e-a4d9-c3fc120d1987"),
                            Name = "Malopolskie",
                            PolishName = "Małopolskie"
                        },
                        new
                        {
                            Id = new Guid("008e4495-51ad-4c2c-ab97-6f93f4aaa42e"),
                            Name = "Mazowieckie",
                            PolishName = "Mazowieckie"
                        },
                        new
                        {
                            Id = new Guid("c90a386f-1866-4792-8bb6-b2f4b244126c"),
                            Name = "Opolskie",
                            PolishName = "Opolskie"
                        },
                        new
                        {
                            Id = new Guid("59fd3598-a69e-47aa-8f0b-09714f605267"),
                            Name = "Podkarpackie",
                            PolishName = "Podkarpackie"
                        },
                        new
                        {
                            Id = new Guid("ac1a4a8e-fd7a-4b00-a3f0-9a6a9d071497"),
                            Name = "Podlaskie",
                            PolishName = "Podlaskie"
                        },
                        new
                        {
                            Id = new Guid("6712c6ae-b8cf-4447-9d63-37f980d5af83"),
                            Name = "Pomorskie",
                            PolishName = "Pomorskie"
                        },
                        new
                        {
                            Id = new Guid("c44814d9-357b-4bc0-b4a2-25d056e1b448"),
                            Name = "Slaskie",
                            PolishName = "Śląskie"
                        },
                        new
                        {
                            Id = new Guid("d22ea8e8-0f4d-4f1d-b04f-15ae2e58cb35"),
                            Name = "Swietokrzyskie",
                            PolishName = "Świętokrzyskie"
                        },
                        new
                        {
                            Id = new Guid("dbc5ecba-6560-40cd-8639-1ca31a606b01"),
                            Name = "Warminsko-mazurskie",
                            PolishName = "Warmińsko-mazurskie"
                        },
                        new
                        {
                            Id = new Guid("b6927901-a3e7-44be-bcfc-0f01e669dc7f"),
                            Name = "Wielkopolskie",
                            PolishName = "Wielkopolskie"
                        },
                        new
                        {
                            Id = new Guid("baadea02-7671-454e-8cc0-dc5b8e71af5d"),
                            Name = "Zachodniopomorskie",
                            PolishName = "Zachodniopomorskie"
                        });
                });

            modelBuilder.Entity("Riva.AdministrativeDivisions.Infrastructure.DataAccess.RivaAdministrativeDivisionsSqlServer.Entities.CityDistrictEntity", b =>
                {
                    b.HasOne("Riva.AdministrativeDivisions.Infrastructure.DataAccess.RivaAdministrativeDivisionsSqlServer.Entities.CityEntity", "City")
                        .WithMany("CityDistricts")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Riva.AdministrativeDivisions.Infrastructure.DataAccess.RivaAdministrativeDivisionsSqlServer.Entities.CityDistrictNameVariantEntity", b =>
                {
                    b.HasOne("Riva.AdministrativeDivisions.Infrastructure.DataAccess.RivaAdministrativeDivisionsSqlServer.Entities.CityDistrictEntity", "CityDistrict")
                        .WithMany("NameVariants")
                        .HasForeignKey("CityDistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Riva.AdministrativeDivisions.Infrastructure.DataAccess.RivaAdministrativeDivisionsSqlServer.Entities.CityEntity", b =>
                {
                    b.HasOne("Riva.AdministrativeDivisions.Infrastructure.DataAccess.RivaAdministrativeDivisionsSqlServer.Entities.StateEntity", "State")
                        .WithMany("Cities")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
