name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Year:yyyy).$(Month).$(DayOfMonth).$(Rev:r)

trigger:
  batch: true
  branches:
    include:
      - master
      - develop
  paths:
    include:
      - 'src/buildingBlocks/src/*'
      - 'src/services/users/*'
      - 'infrastructure/azureResourceManager/Riva.Infrastructure.AzureResourceManager/WebApps/users/*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: 'Global variables'
  - group: 'Dev stage variables'
  - name: buildConfiguration
    value: 'Release'

stages:
  - stage: Test_Application
    displayName: 'Test application'
    jobs:
    - job: Test_Application
      displayName: 'Test application'
      steps:
        - task: DotNetCoreCLI@2
          displayName: 'Run Riva.Users.Domain.Test tests'
          inputs:
            command: 'test'
            projects: 'src/services/users/tests/Riva.Users.Domain.Test/Riva.Users.Domain.Test.csproj'
            arguments: '-c $(buildConfiguration)'
            testRunTitle: 'Riva.Users.Domain.Test tests'
        - task: DotNetCoreCLI@2
          displayName: 'Run Riva.Users.Core.Test tests'
          inputs:
            command: 'test'
            projects: 'src/services/users/tests/Riva.Users.Core.Test/Riva.Users.Core.Test.csproj'
            arguments: '-c $(buildConfiguration)'
            testRunTitle: 'Riva.Users.Core.Test tests'
        - task: DotNetCoreCLI@2
          displayName: 'Run Riva.Users.Infrastructure.Test tests'
          inputs:
            command: 'test'
            projects: 'src/services/users/tests/Riva.Users.Infrastructure.Test/Riva.Users.Infrastructure.Test.csproj'
            arguments: '-c $(buildConfiguration)'
            testRunTitle: 'Riva.Users.Infrastructure.Test tests'
        - task: DotNetCoreCLI@2
          displayName: 'Run Riva.Users.WebApi.Test tests'
          inputs:
            command: 'test'
            projects: 'src/services/users/tests/Riva.Users.Web.Api.Test/Riva.Users.Web.Api.Test.csproj'
            arguments: '-c $(buildConfiguration)'
            testRunTitle: 'Riva.Users.Web.Api.Test tests'

  - stage: Build_And_Push_Docker_Image_For_Develop
    displayName: 'Build and push docker image for develop'
    dependsOn: Test_Application
    condition: and(succeeded('Test_Application'), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))
    variables:
      - group: 'Dev stage variables'
    jobs:
    - job: Build_And_Push_Docker_Image
      displayName: 'Build and push docker image'
      steps:
      - task: Docker@2
        displayName: 'Run docker build and push'
        inputs:
          containerRegistry: '$(ServiceConnection.Azure.ContainerRegistry)'
          repository: '$(Image.RivaUsersWebApi)'
          command: 'buildAndPush'
          Dockerfile: 'src/services/users/src/Riva.Users.Web.Api/Dockerfile.Develop'
          buildContext: '$(System.DefaultWorkingDirectory)'
          tags: '$(Image.Tag)'

  - stage: Push_Infrastructure_Scripts
    displayName: 'Push infrastructure scripts'
    dependsOn: Test_Application
    condition: succeeded('Test_Application')
    pool:
      vmImage: 'ubuntu-latest'
    jobs:
    - job: Push_Infrastructure_Scripts
      displayName: 'Push infrastructure scripts'
      steps:
      - task: PublishBuildArtifacts@1
        displayName: 'Publish infrastructure files'
        inputs:
          PathtoPublish: '$(System.DefaultWorkingDirectory)/infrastructure/azureResourceManager/Riva.Infrastructure.AzureResourceManager/WebApps/users'
          ArtifactName: 'Infrastructure'
          publishLocation: 'Container'

  - stage: Push_Database_Migration_Scripts
    displayName: 'Push database migration scripts'
    dependsOn: Test_Application
    condition: succeeded('Test_Application')
    pool:
      vmImage: 'windows-latest'
    jobs:
    - job: Push_Database_Migration_Scripts
      displayName: 'Push database migration scripts'
      steps:
        - task: DotNetCoreCLI@2
          displayName: "Install dotnet ef"
          inputs:
            command: custom
            custom: tool
            arguments: install --global dotnet-ef --version 3.1.1
        - task: CmdLine@2
          displayName: "Create migratio script for RivaUsersDbContext"
          inputs:
            script: |
              set ASPNETCORE_ENVIRONMENT=Local
              dotnet ef migrations script --project $(system.defaultWorkingDirectory)/src/services/users/src/Riva.Users.Infrastructure/Riva.Users.Infrastructure.csproj --startup-project $(system.defaultWorkingDirectory)/src/services/users/src/Riva.Users.Web.Api/Riva.Users.Web.Api.csproj --context RivaUsersDbContext --configuration Release --output $(build.artifactstagingdirectory)/migrations/rivaUsersDbMigration.sql --idempotent
        - task: PublishBuildArtifacts@1
          displayName: 'Publish build artifact'
          inputs:
            PathtoPublish: '$(build.artifactstagingdirectory)/migrations'
            ArtifactName: 'RivaUsersDatabaseMigrations'
            publishLocation: 'Container'