name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Year:yyyy).$(Month).$(DayOfMonth).$(Rev:r)

trigger:
  batch: true
  branches:
    include:
      - master
      - develop
  paths:
    include:
      - 'src/buildingBlocks/src/Riva.BuildingBlocks.WebApi/*'
      - 'src/apiGateways/web/*'
      - 'infrastructure/azureResourceManager/Riva.Infrastructure.AzureResourceManager/WebApps/apiGateways/web/*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: 'Global variables'
  - group: 'Dev stage variables'
  - name: buildConfiguration
    value: 'Release'

stages:
  - stage: Build_And_Push_Docker_Image_For_Develop
    displayName: 'Build and push docker image for develop'
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/develop')
    variables:
      - group: 'Dev stage variables'
    jobs:
    - job: Build_And_Push_Docker_Image
      displayName: 'Build and push docker image'
      steps:
      - task: Docker@2
        displayName: 'Run docker build and push'
        inputs:
          containerRegistry: '$(ServiceConnection.Azure.ContainerRegistry)'
          repository: '$(Image.RivaWebApiGateway)'
          command: 'buildAndPush'
          Dockerfile: 'src/apiGateways/web/src/Riva.Web.Api.Gateway/Dockerfile.Develop'
          buildContext: '$(System.DefaultWorkingDirectory)'
          tags: '$(Image.Tag)'

  - stage: Push_Infrastructure_Scripts
    displayName: 'Push infrastructure scripts'
    dependsOn: Build_And_Push_Docker_Image_For_Develop
    condition: succeeded('Build_And_Push_Docker_Image_For_Develop')
    pool:
      vmImage: 'ubuntu-latest'
    jobs:
    - job: Push_Infrastructure_Scripts
      displayName: 'Push infrastructure scripts'
      steps:
      - task: PublishBuildArtifacts@1
        displayName: 'Publish infrastructure files'
        inputs:
          PathtoPublish: '$(System.DefaultWorkingDirectory)/infrastructure/azureResourceManager/Riva.Infrastructure.AzureResourceManager/WebApps/apiGateways/web'
          ArtifactName: 'Infrastructure'
          publishLocation: 'Container'